#pragma once

#include <SDL3/SDL_scancode.h>

#include "nu2api/nucore/common.h"

enum HOST_KEYBOARD_ACTION : u8 {
    HOST_KEYBOARD_START,
    HOST_KEYBOARD_MOVE_UP,
    HOST_KEYBOARD_MOVE_DOWN,
    HOST_KEYBOARD_MOVE_LEFT,
    HOST_KEYBOARD_MOVE_RIGHT,
    HOST_KEYBOARD_JUMP,
    HOST_KEYBOARD_PRIMARY_ACTION,
    HOST_KEYBOARD_SPECIAL,
    HOST_KEYBOARD_CHARACTER_SWAP,
    HOST_KEYBOARD_TOGGLE_RIGHT,
};

struct HOST_KEYBOARD_BINDING {
    SDL_Scancode scancode;
    HOST_KEYBOARD_ACTION action;
};

// This is the single keyboard-to-game-action configuration shared by every
// SDL host, including native desktop builds and WebAssembly.
constexpr HOST_KEYBOARD_BINDING HOST_KEYBOARD_BINDINGS[] = {
    {SDL_SCANCODE_RETURN, HOST_KEYBOARD_START},
    {SDL_SCANCODE_UP, HOST_KEYBOARD_MOVE_UP},
    {SDL_SCANCODE_W, HOST_KEYBOARD_MOVE_UP},
    {SDL_SCANCODE_DOWN, HOST_KEYBOARD_MOVE_DOWN},
    {SDL_SCANCODE_S, HOST_KEYBOARD_MOVE_DOWN},
    {SDL_SCANCODE_LEFT, HOST_KEYBOARD_MOVE_LEFT},
    {SDL_SCANCODE_A, HOST_KEYBOARD_MOVE_LEFT},
    {SDL_SCANCODE_RIGHT, HOST_KEYBOARD_MOVE_RIGHT},
    {SDL_SCANCODE_D, HOST_KEYBOARD_MOVE_RIGHT},
    {SDL_SCANCODE_SPACE, HOST_KEYBOARD_JUMP},
    {SDL_SCANCODE_U, HOST_KEYBOARD_JUMP},
    {SDL_SCANCODE_H, HOST_KEYBOARD_PRIMARY_ACTION},
    {SDL_SCANCODE_E, HOST_KEYBOARD_PRIMARY_ACTION},
    {SDL_SCANCODE_J, HOST_KEYBOARD_SPECIAL},
    {SDL_SCANCODE_F, HOST_KEYBOARD_SPECIAL},
    {SDL_SCANCODE_K, HOST_KEYBOARD_CHARACTER_SWAP},
    {SDL_SCANCODE_LCTRL, HOST_KEYBOARD_TOGGLE_RIGHT},
};
