#include "legoapi/ai/core/legoai.h"
#include "legoapi/legoapi_types.h"

i32 LEGO_AIPATHCNX_FULLTERRAIN = 0;
i32 LEGO_AIPATHCNX_DONTTOGGLE = 0;
i32 LEGO_AIPATHCNX_DONT_JUMP_NOW = 0;
i32 LEGO_AIPATHCNX_JUMP_NOW = 0;
i32 LEGO_AIPATHCNX_NO_DESTINATION_CHECK = 0;
i32 LEGO_AIPATHCNX_REQUIRESPERMISSION = 0;
i32 LEGO_AIPATHCNX_BIGJUMP = 0;
i32 LEGO_AIPATHCNX_FORBADDIES = 0;
i32 LEGO_AIPATHCNX_FORGOODIES = 0;
i32 LEGO_AIPATHCNX_R2D2GLIDE = 0;
i32 LEGO_AIPATHCNX_HIGH_JUMP = 0;
i32 LEGO_AIPATHCNX_DOUBLE_JUMP = 0;
i32 LEGO_AIPATHCNX_JUMP = 0;
i32 LEGO_AIPATHCNX_WALLSHUFFLE = 0;
i32 LEGO_AIPATHCNX_BLOCKAGE = 0;
u32 LEGO_AIPATHCNX_MAGNETCLIMB = 0;
u32 LEGO_AIPATHCNX_CLIMB = 0;
