#pragma once

#include "legoapi/gizmo/base/gizactions.h"

struct CHARACTER_CONTEXT_INFO_s {
    const char *name;
    i32 action;
    u32 flags;
    i32 parameter;
};

enum CHARACTER_CONTEXT_INFO_FLAGS : u32 {
    CHARACTER_CONTEXT_INFO_FLAG_USE_FALL_ANIMATION = 0x00000008,
    CHARACTER_CONTEXT_INFO_FLAG_OWNS_ANIMATION = 0x00000010,
    CHARACTER_CONTEXT_INFO_FLAG_DISABLE_BLOB_SHADOW = 0x00020000,
    CHARACTER_CONTEXT_INFO_FLAG_ALLOW_DISABLED_MOVEMENT_SHADOW = 0x00040000,
    CHARACTER_CONTEXT_INFO_FLAG_TERRAIN_ORIGIN_AT_TOP = 0x00080000,
    CHARACTER_CONTEXT_INFO_FLAG_TERRAIN_ORIGIN_AT_POSITION = 0x00100000,
};

// Action and character-context lookup data owned by move.cpp.
extern EXTRAACTIONDATA_s ExtraActionData[];
extern ACTIONINFO_s *ActionInfo;
extern CHARACTER_CONTEXT_INFO_s *CInfo;
